import { StyleSheet } from "react-native";
import type { ThemeColors } from "../../../constants/theme";

const createScreenStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    content: {
      backgroundColor: colors.background,
      paddingBottom: 48,
      flexGrow: 1,
    },
    backLink: {
      alignSelf: 'flex-start',
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
    },
    backLinkText: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: '600',
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      gap: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    nameHeader: {
      width: '100%',
      gap: 4,
    },
    additionalInfoGrid: {
      marginTop: 8,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    additionalInfoItem: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 4,
      borderTopWidth: 1,
      borderColor: colors.border,
      paddingTop: 6,
    },
    additionalInfoLabel: {
      color: colors.textMuted,
      fontSize: 14,
      flex: 1,
    },
    additionalInfoValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'right',
      flexShrink: 0,
    },
    chartHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      justifyContent: 'space-between',
    },
    lastPriceText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '600',
    },
    symbolChangeGroup: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    metaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    symbolText: {
      color: colors.textMuted,
      fontSize: 14,
      marginRight: 10,
    },
    metaDateText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
    },
    percentChange: {
      fontSize: 16,
      fontWeight: '600',
    },
    cardTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '600',
    },
    cardTitleShrink: {
      flex: 1,
      flexShrink: 1,
      minWidth: 0,
      paddingRight: 8,
    },
    detailText: {
      color: colors.textMuted,
      fontSize: 14,
    },
    tooltipText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
    },
    tooltipTextRight: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
      textAlign: 'right',
    },
    chartLoadingRow: {
      marginVertical: 6,
    },
    timeText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 4,
      textAlign: 'center',
      alignSelf: 'center',
    },
    volumeText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: 10,
    },
    chart: {
      width: '100%',
    },
    zoomControls: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexShrink: 0,
      marginLeft: 12,
    },
    zoomBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    zoomBtnText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '600',
    },
    zoomLabel: {
      color: colors.textMuted,
      fontSize: 12,
      minWidth: 40,
      textAlign: 'center',
    },
    tooltip: {
      alignSelf: 'stretch',
      width: '100%',
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
    },
    tooltipGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 4,
    },
    tooltipGridItem: {
      width: '50%',
      paddingRight: 6,
      marginBottom: 4,
    },
    helpBtn: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    helpBtnText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 18,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
    },
    modalCard: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 16,
      width: '100%',
      maxWidth: 420,
      gap: 6,
    },
    modalTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 6,
    },
    modalText: {
      color: colors.text,
      fontSize: 14,
    },
    modalCloseBtn: {
      alignSelf: 'flex-end',
      marginTop: 10,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    modalCloseText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
  });

export default createScreenStyles;
